Repository anitab-org/bridge-in-tech-web, pull requests merged in 2020-09, with the labels that each got.

#83 Test: tests for empty fields on Login form
  src/login/Login.jsx
  src/tests/Login.test.jsx
Labels: Category: Coding, Status: Needs Review, Type: Testing

#89 feat(register): added password confirmation field
  src/register/Register.jsx
  src/tests/Register.test.js
Labels: Category: Coding, Category: User Interface, Status: Needs Review

#91 Fixed : Some Grammatical Errors in Readme
  README.md
Labels: Category: Documentation/Training, Status: Needs Review

#92 feat(login): added password toggle + tests
  src/login/Login.jsx
  src/tests/Login.test.jsx
Labels: Category: Coding, Category: Quality Assurance, Status: Needs Review

#94 Create config.yml
  .github/config.yml
Labels: Category: Documentation/Training, Status: Needs Review

#95 Test: Add tests for validations on personal detail fields
  src/tests/PersonalDetails.test.js
Labels: Category: Quality Assurance, Status: Needs Review

#93 feat(register): added password toggle + tests
  src/register/Register.jsx
  src/tests/Register.test.js
Labels: Category: Coding, Category: Quality Assurance, Status: Needs Review

#88 Test: Write tests for input validations on the Register form
  src/register/Register.jsx
  src/tests/Register.test.js
Labels: Category: Quality Assurance, Status: Needs Review

#99 Feat: Added link to AnitaB.Org in contact menu
  src/Navigation.js
Labels: Category: User Interface, Status: Needs Review

#100 Feat: Create About.jsx
  package-lock.json
  package.json
  src/Routes.js
  src/home/About.css
  src/home/About.jsx
  src/home/Home.jsx
Labels: Category: User Interface, Status: Needs Review

#107 benefit page created
  public/assets/images/benefit1.png
  public/assets/images/benefit2.png
  src/Routes.js
  src/home/Benefit.css
  src/home/Benefit.jsx
Labels: Category: User Interface
