Repository anitab-org/bridge-in-tech-web, pull requests merged in 2020-10, with the labels that each got.

#114 Doc: Add information to README that Heroku servers are unavailable
  README.md
Labels: Category: Documentation/Training, Status: Needs Review

#121 Fix for Bug: Organizations list table content is overflowing outside …
  src/organizations/Organization.css
Labels: Category: User Interface, Type: Bug

#124 Feat: Refactor Navigation style to match MVP as per Figma design
  src/Nav.css
  src/Navigation.js
Labels: Category: User Interface, Status: Needs Review, hacktoberfest-accepted

#125 Feat: Designed UI for 404:Error Page for default redirects.
  src/Routes.js
  src/errorPage/ErrorPage.css
  src/errorPage/ErrorPage.js
Labels: Category: User Interface, Status: Needs Review, hacktoberfest-accepted
