Repository anitab-org/bridge-in-tech-web, pull requests merged in 2020-06, with the labels that each got.

#10 setup: added react base setup - Issue#9
  .gitignore
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
  public/anitab.ico
  public/assets/images/AnitaBLogo.png
  public/css/navbar.css
  public/index.html
  public/manifest.json
  src/Home.jsx
  src/index.css
  src/index.js
  src/routes.js
  src/setupTests.js
Labels: Category: Coding, Category: User Interface, Program: GSOC

#21 Fix#16 Remove .vscode
  .gitignore
  .vscode/launch.json
Labels: Category: Coding

#18 Issue8 register ui - new pr
  package-lock.json
  public/css/main.css
  public/manifest.json
  src/Login.jsx
  src/Routes.js
  src/index.js
  src/register/Register.css
  src/register/Register.jsx
  src/setupTests.js
Labels: Category: Coding, Category: User Interface, Program: GSOC

#25 QA: Add travis file for testing
  .travis.yml
  package-lock.json
  package.json
  src/tests/Register.test.js
  src/tests/__snapshots__/Register.test.js.snap
Labels: Category: Quality Assurance, Program: GSOC

#24 wip: issue20 test cases for Register UI
  package-lock.json
  package.json
  src/register/Register.jsx
  src/tests/Register.test.js
  src/tests/__snapshots__/Register.test.js.snap
Labels: Category: Quality Assurance, Program: GSOC

#26 WIP: Feat: Login UI Issue#14
  package-lock.json
  src/Login.jsx
  src/Routes.js
  src/login/Login.css
  src/login/Login.jsx
  src/myspace/MySpace.jsx
  src/register/Register.jsx
  src/tests/Login.test.jsx
  src/tests/Register.test.js
Labels: Category: Coding, Category: User Interface, Program: GSOC
