Repository anitab-org/bridge-in-tech-web, pull requests merged in 2021-03, with the labels that each got.

#184 Feat: Logo redirects to homepage
  src/Navigation.js
Labels: Category: Coding, Status: Needs Review, Type: Enhancement

#179 Feat: Add code of conduct, terms and privacy policy modal
  src/register/Register.css
  src/register/Register.jsx
  src/register/TermsAndPrivacyPolicyModal.jsx
Labels: Category: Coding, Status: Changes Requested, Type: Enhancement

#182 feat: adding .editorconfig file to maintain code standards.
  .editorconfig
Labels: Category: Coding, Category: Documentation/Training, Status: Changes Requested, Type: Maintenance

#196 Fix: Removed warning generated due to invalid href attribute.
  src/register/Register.jsx
Labels: Category: Coding, Status: Needs Review, Type: Bug

#197 Fix: 404 Page Overlapping
  src/errorPage/ErrorPage.css
  src/errorPage/ErrorPage.js
Labels: Category: Coding, Category: User Interface, Status: Ready to Merge, Type: Bug
