Repository anitab-org/bridge-in-tech-web, pull requests merged in 2021-02, with the labels that each got.

#138 Doc: Add UI Screenshots in Readme
  README.md
Labels: Category: Documentation/Training, Status: Ready to Merge, Type: Maintenance

#165 Fix: Redirect logged-in user to home when going to Register page through URL
  src/AuthContext.js
  src/register/Register.jsx
Labels: Category: Coding, Status: Ready to Merge, Type: Bug

#164 Fix: Stop useEffect from sending multiple requests to the backend
  src/members/Members.jsx
  src/myorganization/EditOrganization.jsx
  src/myorganization/EditPrograms.jsx
  src/myspace/AdditionalInfo.jsx
  src/myspace/PersonalBackground.jsx
  src/myspace/PersonalDetails.jsx
  src/organizations/Organizations.jsx
  src/organizations/Programs.jsx
Labels: Category: Coding, Status: Needs Review, Type: Bug

#146 Fix: Maintain Login and Sign Up buttons layout on Register and Login pages regardless screen size
  src/login/Login.css
  src/login/Login.jsx
  src/register/Register.css
  src/register/Register.jsx
Labels: Category: Coding, Status: Needs Review, Type: Bug

#181 Fix: Fix repeated background on Homepage
  src/home/Home.css
Labels: Category: Coding, Category: User Interface, Status: Ready to Merge, Type: Bug
