Repository anitab-org/bridge-in-tech-web, pull requests merged in 2021-06, with the labels that each got.

#256 Moved GetInTouch files into Home folder
  src/home/GetInTouch.css
  src/home/GetInTouch.jsx
  src/home/Home.jsx
Labels: Category: Documentation/Training, Status: Needs Review, Type: Maintenance

#230 UI: Created Navbar Component
  src/Nav.css
  src/Navigation.js
  src/Routes.js
  src/assets/fonts/MetaPro-Bold.otf
Labels: Open Source Hack, Status: Needs Review

#254 UI: Temporary side navigation for protected pages
  public/index.html
  src/Routes.js
  src/sidebar/Sidebar.jsx
  src/sidebar/sidebar.css
Labels: Category: User Interface, Status: Needs Review, Type: Enhancement
