Repository anitab-org/bridge-in-tech-web, pull requests merged in 2021-04, with the labels that each got.

#206 Doc: add all-contributors bot
  .all-contributorsrc
  README.md
Labels: Category: Documentation/Training, Type: Maintenance

#219 docs: add link to Bridge In Tech zulip stream in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Open Source Hack, Status: Ready to Merge

#221 added description of the project
  public/index.html
Labels: Category: Coding, Open Source Hack, Status: Ready to Merge

#226 Bug: Members list not scrollable on smaller screen sizes
  src/members/Member.css
Labels: Category: User Interface, Open Source Hack, Status: Ready to Merge

#231 Fix: text underline on the Login & Sign Up (blue) buttons
  src/login/Login.css
  src/login/Login.jsx
  src/register/Register.css
  src/register/Register.jsx
Labels: Open Source Hack

#170 Dev: Created deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  _config.yml
  package.json
Labels: Category: Coding, Status: Changes Requested, Type: Maintenance

#220 Fix: prevents protected routes from redirecting to homepage when refreshed
  src/AuthContext.js
Labels: Category: Coding, Open Source Hack, Status: Needs Review

#229 UI: Develop Homepage - Get In Touch section added
  src/Routes.js
  src/assets/fonts/MetaPro-Font/MetaPro-Bold.otf
  src/assets/fonts/MetaPro-Font/MetaPro-Normal.otf
  src/getInTouch/GetInTouch.css
  src/getInTouch/GetInTouch.jsx
  src/home/Home.jsx
Labels: Category: User Interface, Open Source Hack, Status: Changes Requested, Type: Enhancement

#238 added gh url to homepage in package.json
  package.json
  src/Routes.js
Labels: Open Source Hack, Status: Needs Review

#228 Footer Component Added
  src/assets/fonts/MetaPro-Normal.otf
  src/assets/fonts/Poppins-Light.ttf
  src/assets/images/LinkedIn.svg
  src/assets/images/Twitter.svg
  src/assets/images/facebook.svg
  src/assets/images/github.svg
  src/home/Footer.css
  src/home/Footer.jsx
  src/home/Home.jsx
Labels: Category: User Interface, Open Source Hack, Status: Ready to Merge

#235 fix : Username display after login (#166)
  src/login/Login.jsx
Labels: Open Source Hack, Status: Needs Review
